backend:
  # Settings to use Netlify Identity as backend
  name: git-gateway
  repo: christopher-kapic/blog.kapic.io
  branch: master

# Add the route to your images, so Netlify CMS knows where to save uploads to.
media_folder: "src/posts/img"
public_folder: "src/assets"

# You can delete my other comments, but it's helpful to leave the following one here so you don't forget how to run your Netlify CMS.
# If you don't run this command, the CMS will keep giving you errors when you try to login
##
# When you want to use Netlify CMS:
# Run your Eleventy serve commands, (mine is "npm run start")
# In another terminal window, simultaneously run: "npx netlify-cms-proxy-server" for local backend
local_backend: true

publish_mode: editorial_workflow

# Add your collections. Here's an example of multiple collections: 
collections:
# First Collection
  - label: "Blog" 
    name: "blog"
    folder: "src/posts" # Where the new posts should be saved to
    create: true # This allows you to create new instances in the CMS
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumb", widget: "image", default: "pending.png"}
      - { label: "Tags", name: "tags", widget: list }
      - { label: "Body", name: "body", widget: "markdown" }
      # - { label: "Publish" name: "publish", widget: "boolean"}
  ## 
  # Visit https://www.netlifycms.org/docs/widgets/ to learn more about what widgets you can use.
  # Widgets are the data type that field will allow and how the CMS UI will be like for that field , like datetime, number, list of options, boolean, image, code, and more. 
  ##
  # Second Collection
  # It seems to work with or without "" 